---
driver:
  name: docker
  privileged: true

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[raintank_stack::default]
    attributes:
      mysql:
        server_root_password: 'rootpass'
        server_debian_password: 'debpass'
        server_repl_password: 'replpass'
      mariadb:
        server_root_password: 'rootpass'
        server_debian_password: 'debpass'
        server_repl_password: 'replpass'
        use_default_repository: true
      mysqld:
        options:
          binlog_format: 'ROW'
          innodb_autoinc_lock_mode: 2
      grafana:
        domain: "portal.raintank.local"
        root_url: 'http\://portal.raintank.local/'
        db_type: "mysql"
        db_host: "localhost"
        db_port: "3306"
        db_name: "grafana"
        db_user: "root"
        db_password: "rootpass"
      raintank_stack:
        api_key: "eyJrIjoiWmZLTktlNHJ0UFFBdWtVdkRyemNiMjZPNFpralA1M3kiLCJuIjoiY29sbGVjdG9yIiwiaWQiOjF9"
        ping_port: 9090
        kairosdb:
          replication_factor: 1
        nginx:
          use_ssl: false
      influxdb:
        version: "0.8.8"
